spring:
  main:
    banner-mode: console
  datasource:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/auth_server
    username: ${POSTGRESQL_USERNAME:postgres}
    password: ${POSTGRESQL_PASSWORD:odenktools}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
        use_sql_comments: true
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: false
  jackson:
    serialization:
      indent-output: true
      fail-on-empty-beans: false
  devtools:
    restart:
      log-condition-evaluation-delta: false
      enabled: true
# Logging Properties
logging:
  path: logs
  file: ${logging.path}/log.log
  level:
    ROOT: INFO
    com.odenktools.databoot: INFO
    org.hibernate.SQL: error
    org.hibernate.type.descriptor.sql.BasicBinder: error
    org.springframework.web: warn
    org.springframework.boot: warn
# Resource Properties
resources:
  add-mappings: false
# Application Properties
application:
  async:
    core-pool-size: 10
    max-pool-size: 50
    queue-capacity: 10000
