spring:
  main:
    banner-mode: console
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://pg-auth-server:5432/spring_auth_server
    username: ${POSTGRESQL_USERNAME:postgres}
    password: ${POSTGRESQL_PASSWORD:odenktools}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
      poolName: OdenktoolsJPAAuthServerHikariCP
      jdbc-url: jdbc:postgresql:///pg-auth-server:5432/spring_auth_server
      driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
        use_sql_comments: true
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: false
  jackson:
    serialization:
      indent-output: true
      fail-on-empty-beans: false
  devtools:
    restart:
      log-condition-evaluation-delta: false
      enabled: true
# Logging Properties
logging:
  path: logs
  file: ${logging.path}/log.log
  level:
    ROOT: INFO
    com.odenktools: INFO
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
    org.springframework.web: WARN
    org.springframework.boot: WARN
    org.springframework.security: WARN
# Resource Properties
resources:
  add-mappings: false
# Application Properties
application:
  async:
    core-pool-size: 10
    max-pool-size: 50
    queue-capacity: 10000
